dist:
  - xenial

language:
  - cpp

sudo:
  - false

os:
  - linux
  - osx

osx_image:
  - xcode11

addons:
  apt:
    packages:
     - libbz2-dev libfftw3-dev libfishsound1-dev libid3tag0-dev liblo-dev liblrdf0-dev libmad0-dev liboggz2-dev libopus-dev libopusfile-dev libpulse-dev libsamplerate-dev libsndfile-dev libsord-dev libxml2-utils portaudio19-dev qt5-default libqt5svg5-dev libboost-all-dev raptor-utils librubberband-dev mlton

before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; then brew unlink python ; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; then brew install polyml ; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; then brew install qt5 ; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; then export PATH=$PATH:/usr/local/opt/qt5/bin ; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]] ; then ./configure ; else ./repoint install && qmake -r tony.pro ; fi

script:
  - make -j3
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]] ; then sudo make install ; fi
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]] ; then /usr/local/bin/tony -v ; fi
